configure: fix build with separate libtinfo
ncurses has "--with-termlib" build option, which forces some symbols
from libncurses.so to be moved to libtinfo.so.

It caused the following error:

ld: ui.o: undefined reference to symbol 'keypad'
ld: /lib64/libtinfow.so.6: error adding symbols: DSO missing from command line